# Generated by Django 5.0.4 on 2024-08-19 22:23

import main_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[main_app.validators.RangeValidator(1, 99, message='The rating must be between 1.0 and 99.0')]),
        ),
    ]
