# Generated by Django 5.0.4 on 2024-06-28 10:17

from django.db import migrations


def age_group_information(apps, schema_editor):
    person = apps.get_model('main_app', 'Person')
    all_persons = person.objects.all()

    for person in all_persons:
        if person.age <= 12:
            person.age_group = 'Child'
        elif 13 <= person.age <= 17:
            person.age_group = 'Teen'
        else:
            person.age_group = 'Adult'

        person.save()


def reverse_age_group_information(apps, schema_editor):
    person = apps.get_model('main_app', 'Person')
    all_persons = person.objects.all()

    for person in all_persons:
        person.age_group = ''  # Reset the age_group field to empty string or None
        person.save()  # Make sure to save changes


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(age_group_information, reverse_code=reverse_age_group_information)
    ]
