# Generated by Django 5.0.4 on 2024-06-28 11:35

from django.db import migrations
from datetime import datetime, timedelta


def alter_orders(apps, schema_editor):
    Order = apps.get_model('main_app', 'Order')
    all_orders = Order.objects.all()

    for order in all_orders:
        if order.status == 'Pending':
            order.delivery = order.order_date + timedelta(days=3)
        elif order.status == 'Completed':
            order.warranty = '24 months'
        elif order.status == 'Cancelled':
            order.delete()
            continue
        order.save()


def reverse_alter_orders(apps, schema_editor):
    Order = apps.get_model('main_app', 'Order')
    db_alias = schema_editor.connection.alias

    all_orders = Order.objects.using(db_alias).all()

    for order in all_orders:
        if order.status == 'Pending':
            order.delivery = None
        elif order.status == 'Completed':
            order.warranty = 'No warranty'
        order.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(alter_orders, reverse_code=reverse_alter_orders)
    ]
