# Generated by Django 5.0.4 on 2024-08-16 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(error_messages='Enter a valid email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[a-zA-Z\\s]*$'), django.core.validators.MinLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website_url',
            field=models.URLField(error_messages='Enter a valid URL'),
        ),
    ]
