# Generated by Django 5.0.4 on 2024-07-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_registration_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
